language: node_js
node_js:
- 14
script:
- npm run-script build
deploy:
  provider: pages:git
  token:
    secure: H6OgFvZlmNG3mYUNHre0etKgT67AYY/sYm9M5rYtfu6SAEHoSNsDg8kIF7jXf2RZ7giM2DtW+drSk8/le2977u6zGOHcgv3QzVWeCq1bu5Nh5hkRxHDggqml+CdMxdXDQm908qseCye0xpwya44WVm2ZypXRF5G3B65AXMwxBkkvYq5ahRv0kTLkKxNR/K2Q46b5EWzbJEPbpp+Ue9/Jgngv/xfgPNYhQZWcSC+r9RmTDjPQkYwgx0wlF4X6Mg6wK1M0uSBZJ/Hf363nOgoimXgTARlZ3XiK3YE3q2X7ySgowez1NRO7u4VpKgE+52XFjCvVXRZqVGugkz0o2ijj2j1+s38uj6kDnuqHewst9I8vda+SSu1vwFKS8TlAZlscfXuBQSmNUgqFk5PKW/lP2tVd9g++81XduJg3Ew2UgmvMSItTqs6acPa9sx+O3obodK8SySBGQke9+xWUszSJDQOS2D/5PLglG2wwaJ9yjP1rAT6gnyRe8Os+24QEM5kyPnXj02xEynWSF3sFFu+6x+f8Va9c8xBid1tETkvSVJ0JV0Jv4d1uH1aMlDeuqHEV1m95y5GyU85hnSnfbabqvbYNlxjOeiVVEIKU1A6NhQSpQePcLKovQeye2V14wN2RwQkpFgtYg5v/HqBmL36uZrG28/63OJEHTFLUNOnBwfg=
  edge: true
